animal_shelter/animal_shelter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shelter.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animal_shelter/shelter/urls.py
from django.urls import path
from .views import AnimalListView, AdoptionRequestView, AnimalDetailView

urlpatterns = [
  path('', AnimalListView.as_view(), name='animal_list'),
  path('adoption/<int:animal_id>/', AdoptionRequestView.as_view(), name='adoption_request'),
  path('animal/<int:pk>/', AnimalDetailView.as_view(), name='animal_detail'),
]

animal_shelter/shelter/models.py
from django.db import models


class Animal(models.Model):
    name = models.CharField(max_length=30)
    species = models.CharField(max_length=30)
    age = models.IntegerField()
    breed = models.CharField(max_length=30)
    enabled = models.BooleanField(default=True)
    health_history = models.TextField()
    image = models.ImageField(upload_to='animals/', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    is_available = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.name} - {self.species} - {self.breed}'
    
    def summary_description(self):
        if self.description:
            return (self.description[:50] + '...') if len(self.description) > 50 else self.description
        return ''
    
    class Meta:
        verbose_name = 'Animal'
        verbose_name_plural = 'Animals'
        ordering = ['name']

class Adoption(models.Model):
    status_options =(
        ('Under Review', 'Em análise'),
        ('Not Adopted', 'Não adotado'),
        ('Adopted', 'Adotado')
    )
    animal_name = models.CharField(max_length=30)
    species = models.CharField(max_length=30)
    adopter = models.CharField(max_length=30)
    request_date = models.DateField(help_text='aaaa/mm/dd')
    status = models.CharField(max_length=30, choices=status_options, default='Under Review')

    def __str__(self):
        return f'{self.animal_name}: {self.species} - {self.adopter} - {self.request_date} - {self.status}'
    
    class Meta:
        verbose_name = 'Adoption'
        verbose_name_plural = 'Adoptions'
        ordering = ['request_date']


class Staff(models.Model):
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=30)
    role = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}: {self.phone} - {self.role}'
    
    class Meta:
        verbose_name = 'Staff'
        verbose_name_plural = 'Staff'
        ordering = ['name']

animal_shelter/shelter/forms.py
from django import forms
from .models import Animal, Adoption, Staff

class AnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = ['name', 'species', 'age', 'breed', 'health_history']

class AdoptionForm(forms.ModelForm):
    class Meta:
        model = Adoption
        fields = ['animal_name', 'species', 'adopter', 'request_date', 'status']

class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['name', 'phone', 'role']

animal_shelter/shelter/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, FormView, DetailView  # Adicione a importação de DetailView
from .models import Animal, Adoption, Staff
from django.db.models import Q
from .forms import AdoptionForm
from django.contrib import messages
from django.http import HttpResponse


class AnimalListView(ListView):
    model = Animal
    template_name = "animal_list.html"
    context_object_name = "animals"

    def get_queryset(self):
        queryset = Animal.objects.filter(enabled=True)

        # Filter by search query
        search_query = self.request.GET.get("search_term", "")
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query)
                | Q(breed__icontains=search_query)
                | Q(species__icontains=search_query)
                | Q(age__icontains=search_query)
                | Q(health_history__icontains=search_query),
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Include the search query in the context
        context["search_query"] = self.request.GET.get("search_term", "")
        return context


class AdoptionRequestView(FormView):
    template_name = 'adoption_form.html' 
    form_class = AdoptionForm

    def form_valid(self, form):
        
        animal_id = self.kwargs['animal_id']
        animal = get_object_or_404(Animal, id=animal_id)

        
        adoption = form.save(commit=False)
        adoption.animal = animal
        adoption.status = 'Under Review' 
        adoption.save()  

        messages.success(self.request, f'Parabéns! Você adotou {animal.name}. Obrigado por fazer a diferença!')
        return self.render_to_response(self.get_context_data(form=form, animal=animal, adoption_success=True))

    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        animal_id = self.kwargs['animal_id']
        animal = get_object_or_404(Animal, id=animal_id)
        context['animal'] = animal
        context['carers'] = Staff.objects.all()
        return context


# A nova View de Detalhes do Animal
class AnimalDetailView(DetailView):
    model = Animal  
    template_name = 'animal_detail.html'
    context_object_name = 'animal'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        animal = self.get_object()

        last_adoption = Adoption.objects.filter(animal_name=animal.name).last()
        if last_adoption:
            context['adoption_status'] = last_adoption.status
        else:
            context['adoption_status'] = None  

        return context

animal_shelter/shelter/templates/adoption_form.html
{% extends 'layout.html' %}

{% block content %}
  <div class="container">
    {% if not adoption_success %}
      <!-- Títulos e mensagens de boas-vindas -->
      <div class="title text-center my-4">
        <h1>Uma nova família está se formando...</h1>
        <h3>Estamos muito felizes que tenha decidido pela adoção!</h3>
        <h3>A seguir, precisamos de algumas informações para agilizarmos o processo para a chegada de seu novo amigo ❤️</h3>
      </div>

      <!-- Container do formulário -->
      <div class="form-container mx-auto">

        <!-- Título do formulário -->
        <div class="title text-center mb-4">
          <br />
          <h1>Formulário de Adoção</h1>
        </div>
        <p p class="info-pet">
          Animal Escolhido: {{ animal.name }}
          <br />
          Solicitado em: {% now 'd/m/Y H:i' %}
        </p>

        <!-- Formulário de adoção -->
        <form method="post" class="formAdoption-custom">
          {% csrf_token %}

          <div class="col-md-6 mb-3 formAdoption-custom">
            <input type="hidden" name="animal_name" id="id_animal_name" class="input-custom" value="{{ animal.name }}" readonly />
          </div>

          <div class="col-md-6 mb-3 formAdoption-custom">
            <input type="hidden" name="species" id="id_species" class="input-custom" value="{{ animal.species }}" readonly />
          </div>

          <div class="col-md-6 mb-3 formAdoption-custom">
            <select name="adopter" id="id_adopter" required class="input-custom">
              <option value="" disabled selected>Escolha um cuidador</option>
              {% for carer in carers %}
                <option value="{{ carer.id }}">{{ carer.name }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="col-md-6 mb-3 formAdoption-custom">
            <input type="date" name="request_date" id="id_request_date" class="input-custom" required value="{% now 'Y-m-d' %}" />
          </div>

          <div class="col-md-6 mb-3 formAdoption-custom">
            <select name="status" id="id_status" required class="input-custom">
              <option value="Not Adopted">Não Adotado</option>
              <option value="Adopted">Adotado</option>
            </select>
          </div>

          <div class="col-12 text-center mt-4 formAdoption-custom">
            <button type="submit" class="btn btn-primary btn btn-custom btnAdoption-custom">ENVIAR FORMULÁRIO</button>
          </div>
        </form>
      </div>
    {% else %}
        <div class="title text-center my-4">
            <h3 class="text-center" style="margin: 150px;">Adoção concluída com sucesso! Obrigado por fazer a diferença! ❤️</h3>
            <button class="btn btn-primary btn btn-custom" onclick="window.location.href = '/';">Voltar para a página inicial</button>

        </div>
    {% endif %}
  </div>
{% endblock %}

animal_shelter/shelter/templates/animal_detail.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="container">
    <div class="title">
        <h1>Quem é <span class="animal-name">{{animal.name}}</span></h1>
    </div>
    <div class="d-flex animal-detail">
        <div class="left-bar">
            <div class="card-img d-flex justify-content-center">
                <img class="card-img-detail-custom" src="{{ animal.image.url }}" alt="{{ animal.name }}">
            </div>
            <div class="card-body-detail-custom d-flex flex-column">
                <p class="card-text-detail-custom d-flex">
                    <i class="fa-solid fa-paw"></i>
                    {{ animal.species }}
                </p>
                <p class="card-text-detail-custom d-flex">
                    <i class="fa-solid fa-cake-candles"></i>
                    {{ animal.age }} ano(s)
                </p>
                <p class="card-text-detail-custom d-flex">
                    <i class="fa-solid fa-heart"></i>
                    {{ animal.breed }}
                </p>
                <p class="card-text-detail-custom d-flex">
                    <i class="fa-solid fa-circle-info"></i>
                    {% if adoption_status == 'Under Review' %}
                    Animal em processo de adoção
                    {% else %}
                    Disponível para adoção
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="right-bar d-flex flex-column justify-content-between">
            <div class="info-adoption">
                <div class="title title-detail-custom">
                    <h3>Mais informações da adoção</h3>
                </div>
                <div class="description">
                    {{ animal.description }}
                </div>
            </div>

            <div class="info-health">
                <div class="title title-detail-custom">
                    <h3>Histórico de Saúde</h3>
                </div>
                <div class="description">
                    {{ animal.health_history }}
                </div>
            </div>
            <div class="btn-detail-adoption">
                {% if adoption_status == 'Under Review' %}
                    <!-- <p>Em processo de adoção</p> -->
                {% else %}
                    <a href="{% url 'adoption_request' animal.id %}" class="btn btn-custom btn-detail-custom">Adotar {{ animal.name }}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

animal_shelter/shelter/templates/animal_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div class="title">
        <h1>Seu novo amigo está aqui!</h1>
        <h3>Diversos doguíneos e gatinhos ansiosos para conhecer seu novo lar</h3>
    </div>

    <div class="row d-flex list-animals">
        {% for animal in animals %}
            {% if animal.is_available.exists == false %}
                <div class="card card-custom">
                    {% if animal.image %}
                        <div class="card-img-custom">
                            <img class="card-img-top" src="{{ animal.image.url }}" alt="{{ animal.name }}">
                        </div>
                    {% endif %}
                    <div class="card-body card-body-custom">
                        <h5 class="card-title">{{ animal.name }}</h5>
                        <p class="card-text">
                            Raça: {{ animal.breed }}
                        </p>
                        <a href="/animal/{{ animal.id }}" class="btn btn-custom">Quero Adotar</a>
                    </div>
                </div>
            {% endif %}
        {% empty %}
            <div class="col-12">
                <h3>Nenhum animal encontrado com esses filtros</h3>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

animal_shelter/shelter/templates/layout.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Adopt - Seu novo amigo está aqui!</title>

    <!-- bootstrap/custom -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'shelter/custom.css' %}">

    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/ea79fea873.js" crossorigin="anonymous"></script>

</head>

<body>
    <!-- navbar e search bar-->
    <nav class="navbar navbar-expand-lg sticky-top navbar-custom container-fluid">
        <div class="container-fluid">
            <a class="navbar-brand"><a class="navbar-brand-custom" href="/">Pet Adopt</a></a>
            <button class="navbar-toggler navbar-toggle-custom" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fa-solid fa-bars" style="color: white;"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% if request.path == '/' %} <!-- Condicional para verificar se a rota é a página inicial -->
                <form method="get" class="d-flex ms-auto form-custom" role="search">
                    <input class="form-control me-2" type="text" name="search_term" placeholder="Buscar animalzinho"
                        aria-label="Buscar animalzinho" value="{{ search_query }}">
                    <button class="btn" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container-fluid container-fluid-custom">

        {% block content %}

        {% endblock %}
    </div>
    <!-- rodapé com link github-->
    <footer class="footer-custom d-flex">
        <div class="container-fluid d-flex flex-row justify-content-center align-items-center">
            <span class="d-flex footer-item-custom">desenvolvido por <a
                    href="https://github.com/Squad-eniac/abrigo_animais_SquadENIAC" target="_blank">squad
                    ENIAC</a></span>
        </div>
    </footer>
</body>

</html>